### ISSUE TITLE
Build error (broccoli-persistent-filter)

### ISSUE THREAD

**Issue by shanekoss** [kiwiupover/ember-cli-spinjs#189]
Upgrade to Ember 2.18 from 2.16

now I am getting this error on `ember s`

```
Build Error (broccoli-persistent-filter:Babel > [Babel: frontend]) in spin.js

Cannot read property '_parallelBabel' of undefined
```

package.json

```
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "bootstrap-sass": "^3.3.7",
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.1.0",
    "ember-bootstrap": "^1.2.2",
    "ember-browserify": "^1.1.12",
    "ember-changeset": "^1.5.0",
    "ember-changeset-validations": "^1.3.0",
    "ember-cli": "^2.18.2",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.17.0",
    "ember-cli-clipboard": "^0.9.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^1.1.1",
    "ember-cli-deploy-display-revisions": "^1.0.0",
    "ember-cli-deploy-gzip": "^1.0.1",
    "ember-cli-deploy-revision-data": "^1.0.0",
    "ember-cli-deploy-s3": "^1.4.0",
    "ember-cli-deploy-s3-index": "^1.0.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-file-saver": "^1.2.2",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-json-module": "0.0.3",
    "ember-cli-owl-carousel2": "0.0.8",
    "ember-cli-pagination": "^3.1.3",
    "ember-cli-qunit": "^4.3.2",
    "ember-cli-sass": "^7.1.1",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-string-helpers": "^1.9.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-composable-helpers": "^2.0.3",
    "ember-computed-style": "^0.3.0",
    "ember-concurrency": "^0.8.19",
    "ember-cp-validations": "^3.5.3",
    "ember-data": "~2.18.0",
    "ember-drag-drop": "^0.5.1",
    "ember-export-application-global": "^2.0.0",
    "ember-in-viewport": "^3.0.0",
    "ember-link-action": "0.0.38",
    "ember-load-initializers": "^1.0.0",
    "ember-math-helpers": "^2.6.0",
    "ember-one-way-controls": "^2.0.1",
    "ember-perfectscroll": "^0.1.18",
    "ember-power-select": "^2.0.5",
    "ember-promise-helpers": "^1.0.6",
    "ember-resize": "^0.2.2",
    "ember-resolver": "^4.0.0",
    "ember-responsive": "^2.0.5",
    "ember-route-action-helper": "^2.0.6",
    "ember-router-scroll": "^0.7.1",
    "ember-simple-auth": "^1.7.0",
    "ember-simple-auth-token": "^3.0.0",
    "ember-source": "~2.18.0",
    "ember-truth-helpers": "^2.0.0",
    "ember-typography": "^1.0.2",
    "ember-validated-form": "^1.4.2",
    "ember-welcome-page": "^3.2.0",
    "eslint-plugin-ember": "^5.0.0",
    "liquid-fire": "^0.29.5",
    "loader.js": "^4.2.3",
    "perfect-scrollbar": "^1.3.0",
    "ui-ember-slider": "^0.5.0",
    "virtual-each": "^0.6.2"
  },
  "engines": {
    "node": "^4.5 || 6.* || >= 7.*"
  },
  "dependencies": {
    "@babel/core": "^7.0.0",
    "ember-cli-spinjs": "git://github.com/kiwiupover/ember-cli-spinjs.git#ed56b22662bed0da00fdabe9ff10da578d8e2d03",
    "ember-font-awesome": "^4.0.0-rc.4",
    "ember-lazy-video": "^0.3.0",
    "ember-tooltips-fourem": "^3.0.2",
    "ember-truncate-4elements": "^0.3.10",
    "ember-weakmap": "^3.3.0",
    "npm": "^5.8.0"
  }
```

any ideas?

Thanks!!

**Comment by shanekoss** [comment]
btw - I've tried the standard npm install and several branches/commits - all with the same error.  Thanks again.

**Comment by Alexander-Krause** [comment]
Got a similar problem when I updated to `"ember-cli-babel": "^7.1.2"`:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: explorviz-frontend]) in spin.js

Requires Babel "^7.0.0-0", but was loaded with "6.26.3". 
If you are sure you have a compatible version of @babel/core, 
it is likely that something in your build process is loading the wrong version. 
Inspect the stack trace of this error to look for the first entry 
that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

I reckon an update to the newest `ember-cli-babel` in `ember-cli-spin` would solve the problems. Unfortunately, the related CI build fails for the same [reason](https://circleci.com/gh/kiwiupover/ember-cli-spinjs/799).

Here are the log and stack trace for my error:

```
=================================================================================

ENV Summary:

  TIME: Wed Sep 19 2018 08:00:35 GMT+0200 (Mitteleuropäische Sommerzeit)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node/10.9.0/bin/node
  - /usr/local/bin/ember
  - s
  - --environment=mocked
  EXEC_PATH: /usr/local/Cellar/node/10.9.0/bin/node
  TMPDIR: /var/folders/yd/swkq0z650394q4gmfn15b6b00000gn/T
  SHELL: /bin/zsh
  PATH:
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Library/TeX/texbin
  - /opt/X11/bin
  PLATFORM: darwin x64
  FREEMEM: 4495314944
  TOTALMEM: 17179869184
  UPTIME: 2890
  LOADAVG: 2.3056640625,2.09130859375,2.09716796875
  CPUS:
  - Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz - 2300
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.9.0
  - openssl: 1.1.0i
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.22.0
  - v8: 6.8.275.24-node.14
  - zlib: 1.2.11

ERROR Summary:
...skipping...
  - broccoliBuilderErrorStack: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/alex/Git/github.com/explorviz-frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/alex/Git/github.com/explorviz-frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/alex/Git/github.com/explorviz-frontend/node_modules/@babel/plugin-transform-modules-amd/lib/index.js:44:7)
    at /Users/alex/Git/github.com/explorviz-frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)    at /Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at resolve (/Users/alex/Git/github.com/explorviz-frontend/node_modules/broccoli-babel-transpiler/lib/worker.js:11:29)
    at initializePromise (/Users/alex/Git/github.com/explorviz-frontend/node_modules/rsvp/dist/rsvp.js:520:5)
    at new Promise (/Users/alex/Git/github.com/explorviz-frontend/node_modules/rsvp/dist/rsvp.js:995:33)
    at Function.transform (/Users/alex/Git/github.com/explorviz-frontend/node_modules/broccoli-babel-transpiler/lib/worker.js:10:10)
    at process.<anonymous> (/Users/alex/Git/github.com/explorviz-frontend/node_modules/workerpool/lib/worker.js:76:27)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  - codeFrame: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: explorviz-frontend]` plugin. 💥
Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: spin.js
    - line: [undefined]
    - treeDir: /Users/alex/Git/github.com/explorviz-frontend/tmp/broccoli_persistent_filterbabel__babel_explorviz_frontend-input_base_path-3R0OWH6d.tmp
  - message: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:Babel > [Babel: explorviz-frontend]` plugin. 💥
Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
  - name: Error
  - nodeAnnotation: Babel: explorviz-frontend
  - nodeName: broccoli-persistent-filter:Babel > [Babel: explorviz-frontend]
  - originalErrorMessage: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
  - stack: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/alex/Git/github.com/explorviz-frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/alex/Git/github.com/explorviz-frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/alex/Git/github.com/explorviz-frontend/node_modules/@babel/plugin-transform-modules-amd/lib/index.js:44:7)
    at /Users/alex/Git/github.com/explorviz-frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)    at /Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/alex/Git/github.com/explorviz-frontend/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at resolve (/Users/alex/Git/github.com/explorviz-frontend/node_modules/broccoli-babel-transpiler/lib/worker.js:11:29)
    at initializePromise (/Users/alex/Git/github.com/explorviz-frontend/node_modules/rsvp/dist/rsvp.js:520:5)
    at new Promise (/Users/alex/Git/github.com/explorviz-frontend/node_modules/rsvp/dist/rsvp.js:995:33)
    at Function.transform (/Users/alex/Git/github.com/explorviz-frontend/node_modules/broccoli-babel-transpiler/lib/worker.js:10:10)
    at process.<anonymous> (/Users/alex/Git/github.com/explorviz-frontend/node_modules/workerpool/lib/worker.js:76:27)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

================================================================================
```

**Comment by kiwiupover** [comment]
I'm looking into this tonight.  @Alexander-Krause @shanekoss

**Comment by kiwiupover** [comment]
Your issue looks like it is related to `babel 7.0` I think you are using the latest `ember-cli-babel: ^7.0.0` yea looking you have `"@babel/core": "^7.0.0",` Is there a reason you need babel 7?

@shanekoss @Alexander-Krause

**Comment by Alexander-Krause** [comment]
Not a real one I can think of at the moment. I was simply updating all dependencies and this plugin seems to prevent the usage of Babel 7.  Dunno about @shanekoss though.

**Comment by Alexander-Krause** [comment]
Looks like #198 will fix this problem. I will report back after a new release was published.

**Comment by Alexander-Krause** [comment]
Works for me now with 
```
"ember-cli-babel": "^7.1.3",
"ember-cli-spinjs": "2.1.1"
```

Thank you 👍
