### ISSUE TITLE
TypeError: Cannot read property 'modulePrefix' of undefined

### ISSUE THREAD

**Issue by mayatron** [kiwiupover/ember-cli-spinjs#97]
Getting the following error when running tests, on a new project.

```
Died on test #1     at testWrapper (http://localhost:4298/assets/test-support.js:6663:11)
    at test (http://localhost:4298/assets/test-support.js:6677:39)
    at Module.callback (http://localhost:4298/assets/tests.js:132:24)
    at Module.exports (http://localhost:4298/assets/vendor.js:123:32)
    at requireModule (http://localhost:4298/assets/vendor.js:38:18)
    at TestLoader.require (http://localhost:4298/assets/test-loader.js:67:9)
    at TestLoader.loadModules (http://localhost:4298/assets/test-loader.js:58:18): Cannot read property 'modulePrefix' of undefined@ 87 ms
Source: 	
TypeError: Cannot read property 'modulePrefix' of undefined
    at Class.lookupUpConfig (http://localhost:4298/assets/vendor.js:66465:55)
    at Object.applyStr (http://localhost:4298/assets/vendor.js:32892:18)
    at Object.sendEvent (http://localhost:4298/assets/vendor.js:26380:28)
    at Class.trigger [as _super] (http://localhost:4298/assets/vendor.js:44040:25)
    at Class.trigger (http://localhost:4298/assets/vendor.js:54274:19)
    at Class.superWrapper [as trigger] (http://localhost:4298/assets/vendor.js:32725:22)
    at Renderer.willInsertElement (http://localhost:4298/assets/vendor.js:23237:12)
    at ComponentNodeManager_render_instrument (http://localhost:4298/assets/vendor.js:21609:22)
    at Object.instrument (http://localhost:4298/assets/vendor.js:22305:23)
    at ComponentNodeManager_render [as render] (http://localhost:4298/assets/vendor.js:21578:55)
```

Steps to reproduce:

- `ember new myapp` (ember-cli@2.12.1)
- `ember install ember-cli-spinjs`
- `ember g component foo-bar`
- create `app/config/ember-spinner/standard.js` path and file, with file contents: `export default {};`
- add `{{ember-spinner config='standard'}}` to `app/templates/components/foo-bar.hbs`

**Comment by kiwiupover** [comment]
Thanks @mayatron for bring this to my attention I will have a look in the next few days

**Comment by kiwiupover** [comment]
@mayatron are you still having an issue with this?

**Comment by lukemelia** [comment]
I ran into this in a moduleForComponent integration test. Workaround for my app with modulePrefix "editor", in my `beforeEach`:

```js
    this.register('ember-spinner:main', { modulePrefix: 'editor' }, { instantiate: false });
    this.registry.injection('component:ember-spinner', 'emberSpinnerPrefixConfig', 'ember-spinner:main');
```

**Comment by kiwiupover** [comment]
@thanks @lukemelia

**Comment by mayatron** [comment]
@kiwiupover I'm no longer having this issue, thanks for asking.

**Comment by kiwiupover** [comment]
thanks @mayatron closing
